<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _33_invoice2_model extends CI_Model
{

    public $table = 't33_invoice';
    public $id = 'idinvoice';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->from($this->table);
        $this->db->select($this->table . '.*');
        $this->db->select('customer.Nama as customerNama, customer.idcustomer');
        $this->db->select('jo.NoJO');
        $this->db->join('t30_jo jo', 'jo.idjo = ' . $this->table . '.idjo', 'left');
        $this->db->join('t05_customer customer', 'customer.idcustomer = ' . 'jo.idcustomer', 'left');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('customer.Nama', $q);
        $this->db->or_like('jo.NoJO', $q);
		$this->db->or_like('NoInvoice', $q);
		$this->db->or_like('TglInvoice', $q);
		$this->db->from($this->table);
        $this->db->select($this->table . '.*');
        $this->db->select('customer.Nama as customerNama, customer.idcustomer');
        $this->db->select('jo.NoJO');
        $this->db->join('t30_jo jo', 'jo.idjo = ' . $this->table . '.idjo', 'left');
        $this->db->join('t05_customer customer', 'customer.idcustomer = ' . 'jo.idcustomer', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('customer.Nama', $q);
        $this->db->or_like('jo.NoJO', $q);
		$this->db->or_like('NoInvoice', $q);
		$this->db->or_like('TglInvoice', $q);
		$this->db->limit($limit, $start);
        $this->db->from($this->table);
        $this->db->select($this->table . '.*');
        $this->db->select('customer.Nama as customerNama, customer.idcustomer');
        $this->db->select('jo.NoJO');
        $this->db->join('t30_jo jo', 'jo.idjo = ' . $this->table . '.idjo', 'left');
        $this->db->join('t05_customer customer', 'customer.idcustomer = ' . 'jo.idcustomer', 'left');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function getDataByIdJO($idjo)
    {
        $this->db->where('idjo', $idjo);
        $this->db->order_by($this->id, 'desc');
        return $this->db->get($this->table)->row();
    }


}

/* End of file _33_invoice2_model.php */
/* Location: ./application/models/_33_invoice2_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-09 23:45:49 */
/* http://harviacode.com */
