<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _30_jo_model extends CI_Model
{

    public $table = 't30_jo';
    public $id = 'idjo';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idjo', $q);
	$this->db->or_like('NoJO', $q);
	$this->db->or_like('TglJO', $q);
	$this->db->or_like('idcustomer', $q);
	$this->db->or_like('idshipper', $q);
	$this->db->or_like('TglMB', $q);
	$this->db->or_like('idlokasi', $q);
	$this->db->or_like('idarmada', $q);
	$this->db->or_like('idekor', $q);
	$this->db->or_like('iddriver', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idjo', $q);
	$this->db->or_like('NoJO', $q);
	$this->db->or_like('TglJO', $q);
	$this->db->or_like('idcustomer', $q);
	$this->db->or_like('idshipper', $q);
	$this->db->or_like('TglMB', $q);
	$this->db->or_like('idlokasi', $q);
	$this->db->or_like('idarmada', $q);
	$this->db->or_like('idekor', $q);
	$this->db->or_like('iddriver', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _30_jo_model.php */
/* Location: ./application/models/_30_jo_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-21 09:24:01 */
/* http://harviacode.com */