<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _32_csheetd_model extends CI_Model
{

    public $table = 't32_csheetd';
    public $id = 'idcsheetd';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idcsheetd', $q);
		$this->db->or_like('idcsheet', $q);
		$this->db->or_like('idcost', $q);
		$this->db->or_like('Qty', $q);
		$this->db->or_like('idsatuan', $q);
		$this->db->or_like('Harga', $q);
		$this->db->or_like('Jumlah', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idcsheetd', $q);
		$this->db->or_like('idcsheet', $q);
		$this->db->or_like('idcost', $q);
		$this->db->or_like('Qty', $q);
		$this->db->or_like('idsatuan', $q);
		$this->db->or_like('Harga', $q);
		$this->db->or_like('Jumlah', $q);
		$this->db->or_like('created_at', $q);
		$this->db->or_like('updated_at', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _32_csheetd_model.php */
/* Location: ./application/models/_32_csheetd_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-07 02:08:33 */
/* http://harviacode.com */