<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _45_users_menus_model extends CI_Model
{

    public $table = 't45_users_menus';
    public $id = 'idusersmenus';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idusersmenus', $q);
		$this->db->or_like('idusers', $q);
		$this->db->or_like('idmenus', $q);
		$this->db->or_like('rights', $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idusersmenus', $q);
		$this->db->or_like('idusers', $q);
		$this->db->or_like('idmenus', $q);
		$this->db->or_like('rights', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _45_users_menus_model.php */
/* Location: ./application/models/_45_users_menus_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-19 18:56:47 */
/* http://harviacode.com */