<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _31_csheet_model extends CI_Model
{

    public $table = 't31_csheet';
    public $id = 'idcsheet';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->select($this->table . '.*, t30_jo.NoJO');
        $this->db->from($this->table);
        $this->db->join('t30_jo', 't30_jo.idjo = '.$this->table.'.idjo'); //echo $this->db->get_compiled_select();
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idcsheet', $q);
	$this->db->or_like('NoCSheet', $q);
	$this->db->or_like('TglCSheet', $q);
	$this->db->or_like('idjo', $q);
	$this->db->or_like('Total', $q);
	$this->db->or_like('created_at', $q);
	$this->db->or_like('updated_at', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idcsheet', $q);
    	$this->db->or_like('NoCSheet', $q);
    	$this->db->or_like('TglCSheet', $q);
    	$this->db->or_like($this->table.'.idjo', $q);
    	$this->db->or_like('Total', $q);
    	$this->db->limit($limit, $start);
        $this->db->select($this->table . '.*, t30_jo.NoJO');
        $this->db->from($this->table);
        $this->db->join('t30_jo', 't30_jo.idjo = '.$this->table.'.idjo'); //echo $this->db->get_compiled_select();
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _31_csheet_model.php */
/* Location: ./application/models/_31_csheet_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-28 08:23:03 */
/* http://harviacode.com */
