<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class _11_cost_model extends CI_Model
{

    public $table = 't11_cost';
    public $id = 'idcost';
    public $order = 'ASC';
    public $join = 't02_akun';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama as NamaAkun');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idakun = ' . $this->table . '.Akun', 'left');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama as NamaAkun');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idakun = ' . $this->table . '.Akun', 'left');
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like($this->table.'.Nama', $q);
		$this->db->or_like($this->table.'.Kode', $q);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama as NamaAkun');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idakun = ' . $this->table . '.Akun', 'left');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like($this->table.'.Nama', $q);
		$this->db->or_like($this->table.'.Kode', $q);
		$this->db->limit($limit, $start);
        $this->db->select($this->table.'.*');
        $this->db->select($this->join.'.Nama as NamaAkun');
        $this->db->from($this->table);
        $this->db->join($this->join, $this->join . '.idakun = ' . $this->table . '.Akun', 'left');
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file _11_cost_model.php */
/* Location: ./application/models/_11_cost_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-05 00:32:37 */
/* http://harviacode.com */
